CREATE TABLE game
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_game VARCHAR(255)                            NOT NULL,
    price     INT                                     NOT NULL,
    category  VARCHAR(255)                            NOT NULL,
    gender    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_game PRIMARY KEY (id)
);